### ISSUE TITLE
Problem with reload('youtube_dl')

### ISSUE THREAD

**Issue by Dominion0815** [gjedeer/xmpp-youtube-dl-bot#1]
Hi,

I see an error with "reload('youtube_dl')". Bot crashes with this error message.

```
DEBUG: socket       sent  <message to="xxx@xxx.im" type="chat" id="11">
  <body>Finished processing: https://invidio.us/watch?v=xxx   </body>
  </message>
Traceback (most recent call last):
  File "bot.py", line 250, in <module>
    cl.Process(.1)
  File "/usr/lib/python2.7/dist-packages/xmpp/dispatcher.py", line 303, in dispatch
    handler['func'](session,stanza)
  File "bot.py", line 136, in messageCB
    reload('youtube_dl')
TypeError: reload() argument must be module
```

Best regards
Dominion

**Comment by gjedeer** [comment]
Wow, someone other than me is actually using this?

Anyway. Try changing line 136 in bot.py from

    reload('youtube_dl')

to

    reload(youtube_dl)

and let me know if it helped

**Comment by Dominion0815** [comment]
seems to work, thank you very much!

The bot is very usefull for me and I also have a feature request ;)
Is it possible to invite the bot to a MUC with the option to disable output?

Greetings

**Comment by gjedeer** [comment]
Hey, 

Maybe one day when I have more time... https://github.com/gjedeer/xmpp-youtube-dl-bot/issues/3
